api_platform:
    http_cache:
        invalidation:
            enabled: true
            purger: 'app.http_cache.purger.fault_tolerant_souin'
            urls:
                - '%env(CACHE_INVALIDATION_URL)%'

services:
    app.http_cache.purger.fault_tolerant_souin:
        class: App\HttpCache\FaultTolerantSouinPurger
        arguments:
            $inner: '@api_platform.http_cache.purger.souin'
            $logger: '@logger'
