#!/usr/bin/env bash

set -e

# Get kubernetes namespaces
NAMESPACES=$(kubectl get namespaces -l project=true --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')

# Get git repository branches
BRANCHES=$(git ls-remote --heads origin | awk -F '	' '{print $2}' | sed -E 's#^refs/heads/(.*)#\1#g' | sed -E "s/\//-/g" | sed -e 's/\(.*\)/\L\1/')

# Calculate differences between those 2 arrays
DIFF=($(comm -3 <(echo "${NAMESPACES[*]}") <(echo "${BRANCHES[*]}")))

# Only get existing namespaces
NAMESPACES_TO_DELETE=($(comm -12 <(for X in "${DIFF[@]}"; do echo "${X}"; done|sort)  <(for X in "${NAMESPACES[@]}"; do echo "${X}"; done|sort)))

# Remove useless kubernetes namespaces
for i in "${NAMESPACES_TO_DELETE[@]}"; do
    if [[ $DEPLOYMENT_BRANCH != $i ]]
    then
        echo "Remove namespace/release $i"
        helm delete --purge $i || echo "Release $i does not exist"
        kubectl delete namespace $i --wait --cascade || echo "Namespace $i does not exist"
    fi
done
