#!/usr/bin/env bash

set -e

docker-compose down -v
docker-compose pull --ignore-pull-failures
docker-compose build --pull
docker-compose run php composer install -o -n
docker-compose up -d
sleep 20
docker-compose exec php bin/console security:check
docker-compose exec php bin/console doctrine:schema:validate --skip-sync
docker-compose exec php bin/console doctrine:schema:drop --env=test --force
docker-compose exec php bin/console doctrine:schema:create --env=test
docker-compose exec php bin/console messenger:setup-transports --env=test
docker-compose exec php bin/console cache:warmup --env=test
# Run tests one by one because of a bug on fixtures loading
docker-compose exec php bin/phpunit tests/BooksTest.php
docker-compose exec php bin/phpunit tests/ReviewsTest.php
docker-compose exec client yarn install --pure-lockfile
docker-compose exec client yarn jest --ci --reporters=default --reporters=jest-junit --passWithNoTests
docker-compose exec client yarn eslint src
curl -s http://localhost # Client
curl -s http://localhost:81 # Admin
curl -s http://localhost:8080 # API
curl -s http://localhost:8081 # Varnish
curl -k -s https://localhost # Client (HTTP/2)
curl -k -s https://localhost:444 # Admin (HTTP/2)
curl -k -s https://localhost:8443 # API (HTTP/2)
curl -k -s https://localhost:8444 # Varnish (HTTP/2)
