apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql-rw/%s?serverVersion=16&charset=utf8" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Release.Name .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
  better-auth-secret: {{ .Values.pwa.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  oidc-client-secret: {{ .Values.pwa.oidcClientSecret | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  better-auth-database-url: {{ printf "postgresql://%s:%s@%s-postgresql-rw/%s" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Release.Name .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{- end }}
  keycloak-database-name: {{ .Values.keycloak.postgresql.global.postgresql.auth.database | b64enc | quote }}
  keycloak-database-username: {{ .Values.keycloak.postgresql.global.postgresql.auth.username | b64enc | quote }}
  keycloak-database-password: {{ .Values.keycloak.postgresql.global.postgresql.auth.password | b64enc | quote }}
  {{- if .Values.keycloak.auth.createAdminUser }}
  keycloak-admin-username: {{ .Values.keycloak.auth.adminUser | b64enc | quote }}
  keycloak-admin-password: {{ .Values.keycloak.auth.adminPassword | default "!ChangeMe!" | b64enc | quote }}
  {{- end }}
